# Generated by Django 5.2 on 2025-04-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_collection_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('brend', models.CharField(max_length=255, verbose_name='Бренд')),
                ('is_exists', models.BooleanField(default=True, verbose_name='В наличии?')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clint_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('email', models.CharField(max_length=255, verbose_name='Потча')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Имя работника')),
                ('status', models.CharField(max_length=255, verbose_name='Должность')),
                ('employee_phone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Название')),
                ('comment', models.CharField(max_length=255, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереии',
            },
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='collection',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кол-во')),
                ('price_for_count', models.FloatField(verbose_name='Цена за штуку')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.clients', verbose_name='Клиент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Подробности заказа',
                'verbose_name_plural': 'Подробности заказа',
            },
        ),
        migrations.CreateModel(
            name='PhotoBicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image%Y/%m/%d', verbose_name='Изображение')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.bicycle', verbose_name='Велосипед')),
            ],
            options={
                'verbose_name': 'Фото велосипеда',
                'verbose_name_plural': 'Фотографии велосипедов',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.bicycle', verbose_name='Велосипед')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Cloth',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
